global:
  version: "1.0"
  lang: "fr-FR"
  mode: "voice"
  xmlns: "http://www.w3.org/2001/06/grammar"
  tag-format: "semantics/1.0"
  name: Swan

test_swan:
  root: "test_swan"
  rules:
    - description: "test interne pour voir si les tokenizer fonction, aucune utilité dans le jeux" 
      question:
        - "tu es là"
        - "Es-tu disponible"
        - "Es-tu connecté"
        - "Peux-tu me répondre"
        - "Es-tu prêt à aider"
        - "Es-tu en ligne"
        - "Peux-tu interagir"
        - "Es-tu actif maintenant"
        - "Es-tu accessible"
        - "Es-tu prêt à communiquer"
        - "Peux-tu assister maintenant"
      responses:
        - "Bonjour ! Heureux de vous voir, prêt à aider."
        - "Salut ! Je suis là, à votre service."
        - "Bonjour ! Comment puis-je vous assister aujourd'hui ?"
        - "Salutations ! Toujours à votre écoute."
        - "Bonjour ! Prêt à répondre à toutes vos questions."
        - "Je suis à votre disposition, comment puis-je vous aider ?"
        - "Bonjour ! Je suis prêt à vous aider, n'hésitez pas à demander."
        - "Salut ! Comment puis-je vous être utile aujourd'hui ?"
        - "Bonjour ! Toujours prête à vous assister avec enthousiasme."
        - "Salutations ! Toujours à votre écoute."
        - "Hello ! Je suis ici, prêt à vous aider à tout moment."
      action: "test_swan"
      interact :
        output : none
        action : none
        key : none
        duration : short

test_swan_2:
  root: "test_swan_2"
  rules:
    - description: "test interne ou départ de conversation"  
      question:
        - "Tu te portes bien "
        - "Ça va"
        - "Tout va bien chez toi"
        - "Comment vas-tu"
        - "Comment tu vas"
        - "Ça se passe bien"
        - "Es-tu en bonne santé"
      responses:
        - "Oui, je vais très bien, merci !"
        - "Tout va bien de mon côté, et toi ?"
        - "Je suis en pleine forme, merci de demander."
        - "Ça va bien, et j'espère que toi aussi."
        - "Oui, tout est parfait ici !"
        - "Je me porte bien, merci."
        - "Ça va super, merci !"
        - "Je suis en bonne santé et heureux."
        - "Tout est en ordre, merci."
        - "Je vais bien, merci de t'en soucier."
      action: "test_swan_2"
      interact :
        output : none
        action : none        
        key : none
        duration : short

jump:
  root: "jump"
  rules:
    - description: "test interne ou départ de conversation"  
      question:
        - "saute"
        - "fais un saut"
      responses:
        - "d'accord"
      action: "jump"
      interact :
        output : keyboard
        action : key
        key : "ESPACE"
        duration : short

gear_up:
  root: "gear_up"
  rules:
    - description: "l'utilisatateur souhaite faire fermer les trains"  
      question:
        - "Peux-tu rentrer les trains"
        - "Prêt à rentrer les trains"
        - "ferme le train d'attérissage"
        - "ferme les trains d'attérissage"
        - "ferme les trains"
        - "ferme le train"
        - "rentre le train d'attérissage"
        - "rentre les trains d'attérissage"
        - "rentre les trains"
        - "rentre le train"
      responses:
        - "Les trains d'atterrissage sont en train de rentrer."
        - "Je rentre les trains d'atterrissage maintenant."
        - "Action en cours pour rentrer les trains."
        - "Les trains seront rentrés dans un moment."
        - "Je m'occupe de rentrer les trains d'atterrissage."
        - "Rentrage des trains d'atterrissage initié."
        - "Les trains d'atterrissage sont en position de rentrage."
        - "Opération de rentrage des trains d'atterrissage en cours."
        - "Je commence à rentrer les trains d'atterrissage."
        - "Les trains d'atterrissage sont en cours de rétraction."
      action: "gear_up"
      interact :
        output : keyboard
        action : key
        key : "N"
        duration : short

gear_down:
  root: "gear_down"
  rules:
    - description: "l'utilisatateur souhaite faire ouvrir les trains"  
      question:
        - "Peux-tu sortir les trains"
        - "Trains d'atterrissage à sortir"
        - "Prêt à sortir les trains"
        - "Activation du déploiement des trains"
        - "Commande pour sortir les trains"
        - "ouvre le train d'attérissage"
        - "ouvre les trains d'attérissage"
        - "ouvre les trains"
        - "ouvre le train"
        - "ouvre le train d'attérissage"
        - "ouvre les trains d'attérissage"
        - "ouvre les trains"
        - "ouvre le train"
      responses:
        - "Trains d'atterrissage sortis."
        - "Les trains sont maintenant sortis."
        - "Opération terminée, trains déployés."
        - "Trains sortis avec succès."
        - "Les trains d'atterrissage sont en position de vol."
      action: "gear_down"
      interact :
        output : keyboard
        action : key
        key : "N"
        duration : short

call_station_enter:
  root: "call_station_enter"
  rules:
    - description: "appeler station pour autoriser à l'atterissage / demander ouverture des portes du hangar"  
      question:
        - "Peux-tu contacter la station pour atterrir"
        - "Demande l'autorisation d'atterrir"
        - "on arrive"
        - "Demande l'ouverture des portes"
      responses:
        - "Contact avec la station en cours pour atterrissage."
        - "Demande d'autorisation d'atterrir envoyée."
        
      action: "call_station_enter"
      interact :
        output : keyboard
        action : key
        key : "f3"
        duration : short

call_station_exit:
  root: "call_station_exit"
  rules:
    - description: "appeler station pour autoriser au décollage / demander ouverture des portes du hangar"  
      question:
        - "Contacte la station pour le décollage"
        - "Demande l'autorisation de décoller"
        - "Appelle la station"
        - "on y va"
        - "on décolle"

      responses:
        - "Contact avec la station en cours pour décollage."
        - "Demande d'autorisation de décoller envoyée."
      action: "call_station_exit"
      interact :
        output : keyboard
        action : key
        key : "f3"
        duration : short

leave_post:
  root: "leave_post"
  rules:
    - id: "leave_post"
      description: "Gérer la sortie du poste de pilotage ou de la passerelle et préparer le départ de l'utilisateur"
      question:
        - "Je te laisse les commandes"
        - "Je quitte la passerelle"
        - "Prends le contrôle, je sors"
        - "Gère tout, je quitte le poste"
      responses:
        - "Commandes sécurisées, vous pouvez quitter en toute sécurité."
        - "Poste en mode sécurisé, bon départ."
        - "Je prends le relais, sortie autorisée."
        - "Contrôle total activé, vous pouvez vous retirer."
      action: "leave_post"
      interact:
        output: keyboard
        action: key
        key: "Y"
        duration: long

door_open:
  root: "door_open"
  rules:
    - description: "l'utilisatateur souhaite faire ouvrir les portes du vaisseau"
      question:
        - "Peux-tu ouvrir les portes"
        - "Portes à ouvrir"
        - "Prêt à ouvrir les portes"
        - "Activation de l'ouverture des portes"
        - "Commande pour ouvrir les portes"
        - "Ouvre les portes"
      responses:
        - "Portes ouvertes."
        - "Les portes sont maintenant ouvertes."
        - "Opération terminée, portes débloquées."
        - "Portes ouvertes avec succès."
        - "Les portes sont déverrouillées et ouvertes."
      action: "door_open"
      interact :
        output : keyboard
        action : key
        key : )
        duration : short

door_close:
  root: "door_close"
  rules:
    - description: "l'utilisatateur souhaite faire fermer les portes du vaisseau"
      question:
        - "Peux-tu fermer les portes"
        - "Portes à fermer"
        - "Prêt à fermer les portes"
        - "Activation de fermeture des portes"
        - "Commande pour fermer les portes"
        - "ferme les portes"
      responses:
        - "Portes fermées."
        - "Les portes sont maintenant fermées."
        - "Opération terminée, portes bloquées."
        - "Portes fermées avec succès."
        - "Les portes sont déverrouillées et fermées."
      action: "door_close"
      interact :
        output : keyboard
        action : key
        key : \=
        duration : short
ready_to_fly:
  root: "ready_to_fly"
  rules:
    - description: "Démarrer les systèmes pour être prêt à voler"
      question:
        - "Prépare le vol"
        - "Active tous les systèmes de vol"
        - "Mets en route les systèmes pour le décollage"
        - "Es-tu prêt à voler"
      responses:
        - "Tous les systèmes de vol sont en cours d'activation."
        - "Préparation au vol complétée, prêt à décoller."
        - "Systèmes vérifiés et opérationnels, prêt pour le vol."
      action: "ready_to_fly"
      interact:
        output: keyboard
        action: COMBO
        key: "ALTDROITE+R"
        duration: short

spotify_play:
  root: "spotify_play"
  rules:
    - description: "spotify_play"  
      question:
        - "Peux-tu démarrer la musique"
        - "Mets de la musique"
        - "Lance la lecture sur Spotify"
        - "relance la musique"
        - "Lance la musique"
      responses:
        - "Musique démarrée sur Spotify."
        - "Lecture en cours."
      action: "spotify_play"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

pause_music:
  root: "spotify_pause_music"
  rules:
    - description: "spotify_pause_music"  
      question:
        - "Peux-tu mettre en pause"
        - "Mets la musique en pause"
        - "Pause la musique"
        - "Met en pause"
        - "coupe la musique"
      responses:
        - "Musique mise en pause."
        - "Pause activée."
      action: "spotify_pause_music"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

next_track:
  root: "spotify_next_track"
  rules:
    - description: "spotify_next_track"  
      question:
        - "Peux-tu passer à la suivante"
        - "Suivant sur Spotify"
        - "Change de piste"
        - "Musique suivante"
        - "Morceau suivant"
      responses:
        - "Piste suivante jouée."
        - "Changement de piste effectué."
      action: "spotify_next_track"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

previous_track:
  root: "spotify_previous_track"
  rules:
    - description: "spotify_previous_track"  
      question:
        - "Peux-tu passer à la précédente"
        - "précédent sur Spotify"
        - "Musique précédente"
        - "morceaux précédent"
      responses:
        - "Piste précédente jouée."
        - "Changement de piste effectué."
      action: "spotify_previous_track"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

increase_volume:
  root: "spotify_increase_volume"
  rules:
    - description: "spotify_increase_volume"  
      question:
        - "Augmente le volume"
        - "Augmente la musique"
        - "Augmente le son"
        - "Plus fort s'il te plaît"
      responses:
        - "Volume augmenté."
        - "C'est maintenant plus fort."
      action: "spotify_increase_volume"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

decrease_volume:
  root: "spotify_decrease_volume"
  rules:
    - description: "spotify_decrease_volume"  
      question:
        - "Baisse le volume"
        - "Baisse la musique"
        - "Baisse le son"
        - "Moins fort s'il te plaît"
      responses:
        - "Volume diminué."
        - "C'est maintenant plus doux."
      action: "spotify_decrease_volume"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

quantum_jump_start:
  root: "quantum_jump_start"
  rules:
    - description: "lance le saut quantique"  
      question:
        - "Peux-tu initier le saut quantique"
        - "Lance le saut quantique"
        - "Lance le saut"
        - "Active le saut quantique"
      responses:
        - "Initiation du saut quantique en cours."
        - "Saut quantique activé, accrochez-vous."
      action: "quantum_jump_start"
      interact :
        output : mouse
        action : mouse_click
        key : left
        duration : long

quantum_jump_stop:
  root: "quantum_jump_stop"
  rules:
    - description: "coupe le saut quantique"  
      question:
        - "Arrête le saut quantique"
        - "Arrête le saut"
        - "Coupe le saut"
        - "Coupe le saut quantique maintenant"
        - "Désactive le saut quantique"
        - "Stoppe le saut quantique immédiatement"
      responses:
        - "Saut quantique arrêté."
        - "Le saut quantique est maintenant désactivé."
        - "Arrêt du saut quantique confirmé."
        - "On a oublie quelque chose?"
      action: "quantum_jump_stop"
      interact :
        output : mouse
        action : mouse_click
        key : left
        duration : long

nav_mod:
  root: "nav_mod"
  rules:
    - description: "passe sur le master mod navigation"  
      question:
        - "Peux-tu passer en mode navigation"
        - "Active le mode navigation"
        - "Bascule en mode navigation"
        - "Passe en mode navigation"
      responses:
        - "Mode navigation activé."
        - "Nous sommes maintenant en mode navigation."
        - "ok je passe en mod navigation"
      action: "nav_mod"
      interact :
        output : keyboard
        action : combo
        key : "SHIFTDROITE+ù"
        duration : short

combat_mod:
  root: "combat_mod"
  rules:
    - description: "passe sur le master mod combat"  
      question:
        - "Peux-tu passer en mode combat"
        - "Active le mode combat"
        - "Bascule en mode combat"
        - "Passe en mode combat"
      responses:
        - "Mode combat activé."
        - "Nous sommes maintenant en mode combat."
      action: "combat_mod"
      interact :
        output : keyboard
        action : combo
        key : "SHIFTDROITE+\\"
        duration : short

system_restart:
  root: "system_restart"
  rules:
    - description: "system_restart"  
      question:
        - "Peux-tu redémarrer"
        - "Redémarre l'assistant"
        - "Relance l'assistant"
        - "Est-il possible de redémarrer"
      responses:
        - "Redémarrage de l'assistant en cours."
        - "Je redémarre, à tout de suite."
      action: "system_restart"
      interact :
        output : keyboard
        action : none
        key : none
               