global:
  version: "1.0"
  lang: "fr-FR"
  mode: "voice"
  xmlns: "http://www.w3.org/2001/06/grammar"
  tag-format: "semantics/1.0"
  name: Swan

test:
  root: "tu_es_la"
  rules:
    - description: "test interne pour voir si les tokenizer fonction, aucune utilité dans le jeux" 
      question:
        - "tu es là"
        - "Es-tu disponible"
        - "Es-tu connecté"
        - "Peux-tu me répondre"
        - "Es-tu prêt à aider"
        - "Es-tu en ligne"
        - "Peux-tu interagir"
        - "Es-tu actif maintenant"
        - "Es-tu accessible"
        - "Es-tu prêt à communiquer"
        - "Peux-tu assister maintenant"
      responses:
        - "Bonjour ! Heureux de vous voir, prêt à aider."
        - "Salut ! Je suis là, à votre service."
        - "Bonjour ! Comment puis-je vous assister aujourd'hui ?"
        - "Salutations ! Toujours à votre écoute."
        - "Bonjour ! Prêt à répondre à toutes vos questions."
        - "Je suis à votre disposition, comment puis-je vous aider ?"
        - "Bonjour ! Je suis prêt à vous aider, n'hésitez pas à demander."
        - "Salut ! Comment puis-je vous être utile aujourd'hui ?"
        - "Bonjour ! Toujours prête à vous assister avec enthousiasme."
        - "Salutations ! Toujours à votre écoute."
        - "Hello ! Je suis ici, prêt à vous aider à tout moment."
      action: "test_de_swan"
      interact :
        output : none
        action : none
        key : none
        duration : short

test2:
  root: "comment_tu_vas"
  rules:
    - description: "test interne ou départ de conversation"  
      question:
        - "Tu te portes bien "
        - "Ça va"
        - "Tout va bien chez toi"
        - "Comment vas-tu"
        - "Comment tu vas"
        - "Ça se passe bien"
        - "Es-tu en bonne santé"
      responses:
        - "Oui, je vais très bien, merci !"
        - "Tout va bien de mon côté, et toi ?"
        - "Je suis en pleine forme, merci de demander."
        - "Ça va bien, et j'espère que toi aussi."
        - "Oui, tout est parfait ici !"
        - "Je me porte bien, merci."
        - "Ça va super, merci !"
        - "Je suis en bonne santé et heureux."
        - "Tout est en ordre, merci."
        - "Je vais bien, merci de t'en soucier."
      action: "comment_tu_vas"
      interact :
        output : none
        action : none        
        key : none
        duration : short

gear_up:
  root: "gear_up"
  rules:
    - description: "l'utilisatateur souhaite faire fermer les trains"  
      question:
        - "Peux-tu rentrer les trains"
        - "Prêt à rentrer les trains"
        - "ferme le train d'attérissage"
        - "ferme les trains d'attérissage"
        - "ferme les trains"
        - "ferme le train"
        - "rentre le train d'attérissage"
        - "rentre les trains d'attérissage"
        - "rentre les trains"
        - "rentre le train"
      responses:
        - "Les trains d'atterrissage sont en train de rentrer."
        - "Je rentre les trains d'atterrissage maintenant."
        - "Action en cours pour rentrer les trains."
        - "Les trains seront rentrés dans un moment."
        - "Je m'occupe de rentrer les trains d'atterrissage."
        - "Rentrage des trains d'atterrissage initié."
        - "Les trains d'atterrissage sont en position de rentrage."
        - "Opération de rentrage des trains d'atterrissage en cours."
        - "Je commence à rentrer les trains d'atterrissage."
        - "Les trains d'atterrissage sont en cours de rétraction."
      action: "gear_up"
      interact :
        output : keyboard
        action : pressKey
        key : n
        duration : short

gear_down:
  root: "gear_down"
  rules:
    - description: "l'utilisatateur souhaite faire ouvrir les trains"  
      question:
        - "Peux-tu sortir les trains"
        - "Trains d'atterrissage à sortir"
        - "Prêt à sortir les trains"
        - "Activation du déploiement des trains"
        - "Commande pour sortir les trains"
        - "ouvre le train d'attérissage"
        - "ouvre les trains d'attérissage"
        - "ouvre les trains"
        - "ouvre le train"
        - "ouvre le train d'attérissage"
        - "ouvre les trains d'attérissage"
        - "ouvre les trains"
        - "ouvre le train"
      responses:
        - "Trains d'atterrissage sortis."
        - "Les trains sont maintenant sortis."
        - "Opération terminée, trains déployés."
        - "Trains sortis avec succès."
        - "Les trains d'atterrissage sont en position de vol."
      action: "gear_down"
      interact :
        output : keyboard
        action : pressKey
        key : n
        duration : short

door_open:
  root: "door_open"
  rules:
    - description: "l'utilisatateur souhaite faire ouvrir les portes du vaisseau"
      question:
        - "Peux-tu ouvrir les portes"
        - "Portes à ouvrir"
        - "Prêt à ouvrir les portes"
        - "Activation de l'ouverture des portes"
        - "Commande pour ouvrir les portes"
        - "Ouvre les portes"
      responses:
        - "Portes ouvertes."
        - "Les portes sont maintenant ouvertes."
        - "Opération terminée, portes débloquées."
        - "Portes ouvertes avec succès."
        - "Les portes sont déverrouillées et ouvertes."
      action: "door_open"
      interact :
        output : keyboard
        action : pressKey
        key : none
        duration : short

door_close:
  root: "door_close"
  rules:
    - description: "l'utilisatateur souhaite faire fermer les portes du vaisseau"
      question:
        - "Peux-tu fermer les portes"
        - "Portes à fermer"
        - "Prêt à fermer les portes"
        - "Activation de fermeture des portes"
        - "Commande pour fermer les portes"
        - "ferme les portes"
      responses:
        - "Portes fermées."
        - "Les portes sont maintenant fermées."
        - "Opération terminée, portes bloquées."
        - "Portes fermées avec succès."
        - "Les portes sont déverrouillées et fermées."
      action: "door_close"
      interact :
        output : keyboard
        action : pressKey
        key : none
        duration : short

spotify_play:
  root: "spotify_play"
  rules:
    - description: "spotify_play"  
      question:
        - "Peux-tu démarrer la musique"
        - "Mets de la musique"
        - "Lance la lecture sur Spotify"
        - "relance la musique"
        - "Lance la musique"
      responses:
        - "Musique démarrée sur Spotify."
        - "Lecture en cours."
      action: "spotify_play"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

pause_music:
  root: "spotify_pause_music"
  rules:
    - description: "spotify_pause_music"  
      question:
        - "Peux-tu mettre en pause"
        - "Mets la musique en pause"
        - "Pause la musique"
        - "Met en pause"
      responses:
        - "Musique mise en pause."
        - "Pause activée."
      action: "spotify_pause_music"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

next_track:
  root: "spotify_next_track"
  rules:
    - description: "spotify_next_track"  
      question:
        - "Peux-tu passer à la suivante"
        - "Suivant sur Spotify"
        - "Change de piste"
        - "Musique suivante"
        - "Morceau suivant"
      responses:
        - "Piste suivante jouée."
        - "Changement de piste effectué."
      action: "spotify_next_track"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

previous_track:
  root: "spotify_previous_track"
  rules:
    - description: "spotify_previous_track"  
      question:
        - "Peux-tu passer à la précédente"
        - "précédent sur Spotify"
        - "Musique précédente"
        - "morceaux précédent"
      responses:
        - "Piste précédente jouée."
        - "Changement de piste effectué."
      action: "spotify_previous_track"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

increase_volume:
  root: "spotify_increase_volume"
  rules:
    - description: "spotify_increase_volume"  
      question:
        - "Augmente le volume"
        - "Augmente la musique"
        - "Augmente le son"
        - "Plus fort s'il te plaît"
      responses:
        - "Volume augmenté."
        - "C'est maintenant plus fort."
      action: "spotify_increase_volume"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

decrease_volume:
  root: "spotify_decrease_volume"
  rules:
    - description: "spotify_decrease_volume"  
      question:
        - "Baisse le volume"
        - "Baisse la musique"
        - "Baisse le son"
        - "Moins fort s'il te plaît"
      responses:
        - "Volume diminué."
        - "C'est maintenant plus doux."
      action: "spotify_decrease_volume"
      interact :
        output : keyboard
        action : none
        key : none
        duration : short

system_restart:
  root: "system_restart"
  rules:
    - description: "system_restart"  
      question:
        - "Peux-tu redémarrer"
        - "Redémarre l'assistant"
        - "Est-il possible de redémarrer"
      responses:
        - "Redémarrage de l'assistant en cours."
        - "Je redémarre, à tout de suite."
      action: "system_restart"
      interact :
        output : keyboard
        action : none
        key : none
               