global:
  version: '1.0'
  lang: fr-FR
  mode: voice
  xmlns: http://www.w3.org/2001/06/grammar
  tag-format: semantics/1.0
  name: Swan
test_swan:
  root: test_swan
  rules:
    - action: test_swan
      description: >-
        test interne pour voir si le tokenizer fonction, aucune utilité dans le
        jeux
      questions:
        - tu es là
        - Es-tu disponible
        - Es-tu connecté
        - Peux-tu me répondre
        - Es-tu prêt à aider
        - Es-tu en ligne
        - Peux-tu interagir
        - Es-tu actif maintenant
        - Es-tu accessible
        - Es-tu prêt à communiquer
        - Peux-tu assister maintenant
      responses:
        - Non, je dort encore papa
        - Bonjour ! Heureux de vous voir, prêt à aider.
        - Salut ! Je suis là, à votre service.
        - Bonjour ! Comment puis-je vous assister aujourd'hui ?
        - Salutations ! Toujours à votre écoute.
        - Bonjour ! Prêt à répondre à toutes vos questions.
        - Je suis à votre disposition, comment puis-je vous aider ?
        - Bonjour ! Je suis prêt à vous aider, n'hésitez pas à demander.
        - Salut ! Comment puis-je vous être utile aujourd'hui ?
        - Bonjour ! Toujours prête à vous assister avec enthousiasme.
        - Salutations ! Toujours à votre écoute.
        - Hello ! Je suis ici, prêt à vous aider à tout moment.
      interact:
        output: none
test_swan_2:
  root: test_swan_2
  rules:
    - action: test_swan_2
      description: >-
        test interne pour voir si le tokenizer fonction, aucune utilité dans le
        jeux
      questions:
        - 'Tu te portes bien '
        - Ça va
        - Tout va bien chez toi
        - Comment vas-tu
        - Comment tu vas
        - Ça se passe bien
        - Es-tu en bonne santé
      responses:
        - Oui, je vais très bien, merci !
        - Tout va bien de mon côté, et toi ?
        - Je suis en pleine forme, merci de demander.
        - Ça va bien, et j'espère que toi aussi.
        - Oui, tout est parfait ici !
        - Je me porte bien, merci.
        - Ça va super, merci !
        - Je suis en bonne santé et heureux.
        - Tout est en ordre, merci.
        - Je vais bien, merci de t'en soucier.
      interact:
        output: none
